### ISSUE TITLE
Extra code in generated migrations

### ISSUE THREAD

**Issue by Aurielle** [iPublikuj/doctrine-phone#1]
I'm starting to use this extension and currently writing migrations for my database schema, and `migrations:diff` command is generating this piece of code:

	$this->addSql('ALTER TABLE users ALTER telephone TYPE VARCHAR(255)');
	$this->addSql('ALTER TABLE users ALTER telephone DROP DEFAULT');

This is in my opinion wrong, as the targeted column is already VARCHAR(255) and it has NULL set as a default value. I'm using postgresql. The column is defined as follows:

	/**
	 * @var Phone
	 * @ORM\Column(type="phone", unique=true, nullable=true)
	 */
	private $telephone;

I think the code shouldn't be generated at all, because the type definition is, if I recall correctly, compatible with normal string type, which was set at this column before.

No PR because I haven't had time to dig into this deeper, sorry. Feel free to prove me wrong though, I may be just a bit too sleepy to think straight :)

**Comment by akadlec** [comment]
Yes you are right, there is something wrong. Right now i'm without free time to do the investigation, so if you have time, please take a look in it. Thanks
