### ISSUE TITLE
Problem with DI

### ISSUE THREAD

**Issue by jecminek** [ipublikuj/doctrine-phone#6]
Hi, I have a problem with DI in my Nette app. I tried to implement your doctine-phone, but when I use your solution from documentation something gone wrong. Is it any way how to inject missing $phoneHelper or ..?

> Service 'doctrinePhone.subscriber' (type of IPub\DoctrinePhone\Events\PhoneObjectSubscriber): Service of type IPub\Phone\Phone needed by $phoneHelper in IPub\DoctrinePhone\Events\PhoneObjectSubscriber::__construct() not found. Did you register it in configuration file?

config.neon
`extensions:
    ...
    doctrinePhone: IPub\DoctrinePhone\DI\DoctrinePhoneExtension`

My user entity (I using MagicAccessors instead of BaseEntity)
```
use Kdyby\Doctrine\Entities\MagicAccessors;
class User {
    use Identifier;
    use MagicAccessors;
    /**
     * Telefonní číslo
     * @ORM\Column(type="phone")
     * @var Phone\Entities\Phone
     */
    protected $phone;
    /**
     * @var $phone IPub\Phone\Entities\Phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }
    /**
     * @return IPub\Phone\Entities\Phone
     */
    public function getPhone()
    {
        return $this->phone;
    }
...
}
```

**Comment by akadlec** [comment]
you have to register extension [ipub/phone](https://github.com/ipublikuj/phone) too. Doctrine phone is only extension of parent extension
